name = "examples"
description = "Examples for the network library"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]

executables = ["examples"]

[[depends-on]]
network = "*"

[[pins]]
network = { path='..' }
